spring.application.name=Inventario-Espaco-Vista-System
server.port=8080

spring.sql.init.mode=always
# BANCO DE DADOS (POSTGRESQL)
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/db_inventario_vista
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------------------------------------
# JPA E HIBERNATE
# ---------------------------------------------------------
# Trocamos para NONE porque quem vai criar as tabelas é o schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ---------------------------------------------------------
# UPLOAD DE ARQUIVOS E FOTOS
# ---------------------------------------------------------
grupoginga.storage.local.diretorio=uploads/fotos_alunos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=${APP_UPLOAD_PATH:uploads}